language: python
python:
    - "2.6"
    - "2.7"

notifications:
  email:
    - hschlichting@mozilla.com
    - ben@groovie.org
  irc: "irc.mozilla.org#services-dev"

before_install:
    - sudo apt-get install zookeeper

install:
    - make

script:
    - export ZOOKEEPER_PATH=/usr/share/java
    - make test
